### ISSUE TITLE
Organization partOf URL

### ISSUE THREAD

**Issue by chrisbloe** [nhsconnect/gpconnect#112]
The [partOf specification](http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/gpconnect-organization-1-dict.html#Organization.partOf.reference) does not mandate how the URL must be formatted - it could a full URL, partual URL and optionally point to a FHIR server.

Do we want to restrict to something more specific?

**Comment by Dunmail** [comment]
The reference may be a relative reference, in which case it is relative
to the service base URL, or an absolute URL that resolves to the
location where the resource is found. The reference may be version
specific or not. If the reference is not to a FHIR RESTful server, then
it should be assumed to be version specific. Internal fragment
references (start with '#') refer to contained resources.


Is this not sufficient?



--

Dr Dunmail Hodkinson

Chief Technology Officer at Black Pear Software Ltd



dunmail@blackpear.com | +44 (0)1434 674396 | +44 (0)7787 410589 | skype:
dunmail.hodkinson
www.blackpear.com



This E-mail is confidential and may also be privileged. It must not be
disclosed to any other person or party without the prior authority of
Black Pear Software Limited. To do so may be unlawful. If you are not
the intended recipient of this, please notify us immediately and delete
the e-mail received.


This e-mail and any attached files have been checked for viruses.
Although we employ virus protection software, we cannot accept any
responsibility for any loss or damage to your systems due to viruses or
malicious code not detected.


Any views or opinions contained within this message are solely those of
the author and do not necessarily represent those of Black Pear
Software Limited.






On Wed, Mar 29, 2017, at 09:39 AM, Kris Bloe wrote:

> The partOf specification[1] does not mandate how the URL must be
> formatted - it could a full URL, partual URL and optionally point to a
> FHIR server.
> Do we want to restrict to something more specific?



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
> 




Links:

  1. http://data.developer.nhs.uk/fhir/candidaterelease-170816-getrecord/Profile.GetRecordQueryResponse-HTMLView/gpconnect-organization-1-dict.html#Organization.partOf.reference
  2. https://github.com/nhsconnect/gpconnect/issues/112

**Comment by michaelmeasures** [comment]
@chrisbloe we also have the Common API Guidance which has a section on how we expect resource references to be populated.

https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#resource-references

We decided to go with local references:

GP Connect clients and servers SHALL utilise local relative references only and as such the resources will be expected to reside on the same server.

This is inline with what has been done for other FHIR RESTful APIs such as the Argonaut work.

**Comment by michaelmeasures** [comment]
@chrisbloe I'm closing this out as a won't fix as the same profiles could be reused in multiple settings (i.e. not just GP Connect) and not just for the RESTful paradigm (i.e. in documents, messaging, pub/sub etc). So performing a blanked change across all FHIR profiles seems a  bit heavy handed.
