### ISSUE TITLE
Register a patient - temporary patients

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#139]
foundations_use_case_register_a_patient.html

"Provider systems SHALL register the new Patient resource as a temporary patient record once a PDS trace has been confirmed."

Is there a time limit to "temporary?"
What guidance has been given to providers around the use of a "temporary patient". Is there a danger that clinical data is written to a "temporary" patient at a federated practice may be lost, or that the consulation with the patient at the federated practice does not pull in the full medical record?

Why is it necessary to create a temporary patient at all? Should not a provider use GPconnect apis to access the primary record?

**Comment by michaelmeasures** [comment]
@briandiggle it's a temporary patient from the point of view of the GP practice (i.e. you're a visitor/on holiday etc.) not PDS. Hence, you are still fully traced on PDS but the GP isn't your usual GP (and hence you don't have an existing record). Note, a vendor has recently asked a question around putting a time limit on being a temporary patient, so we'll need to explore that some more. However, in the workshops it was made to sound like this was already commonly done; so existing time limits would apply. Finally, in terms of data being lots again we're relying on existing manual workflows to ensure that any pertinent data makes its way back to your usual GP. So I personally don't see this as being a risk but it would be worth documenting the business requirements / use cases and any decision decisions so the expected behavior can be firmly established.

**Comment by briandiggle** [comment]
OK-  we'll need to make clear in the specification where responsibility lies in terms of data written to a temporary patient record at federated organisation

**Comment by james-answer** [comment]
I was just looking over the register patient requirements for the automated test suite and on the following register patient page:

https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#error-handling

It says under the error section:
   "the registerPatient demographics don’t match that of the triggered PDS trace."

This implies that the provider should perform a PDS trace before registering the temporary patient. This seems like it relates to the issue raised by Brian above. Are we saying that the provider shouldn't do a PDS trace and we will rely on the consumer performing a PDS trace before sending in the patient details? If so the register patient specification page needs updating.

**Comment by michaelmeasures** [comment]
@james-answer both the consumer and provider have to do a PDS trace. The consumer to be able to provide the validated NHS number and date of birth (and potentially other demographics). The provider to then be able to reliably assimilate and register a temporary patient into the target GP system. The need to perform a PDS trace at the provider side was discussed in a workshop and is the same workflow as what currently happens when a temporary patient turns up at a GP practice they've not been to before (say they're on holiday) and needs to be seen.

**Comment by james-answer** [comment]
Closed as work will be done to clarify all points above on #233
