### ISSUE TITLE
gpc.getschedule what classes as a slot within the requested time period

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#144]
In the following part of the spec:

https://nhsconnect.github.io/gpconnect/appointments_use_case_search_for_free_slots.html#payload-response-body

It says: "SHALL include the free Slot details for the organisation which have a freeBusyType status of “free” and fall within the requested date range."

What should suppliers do if the slot date range spans the boundary, for example what if the start date of the slot is within the date range but the slot end date is outside of the supplied date range, should the slot be returned. Same applies at the other end where the slot start is before the supplied date range but the slot end date is in the date range.

**Comment by michaelmeasures** [comment]
@james-answer I think it's sensible to return free slots that span the boundary otherwise if you wanted to render a free-busy view you wouldn't know if the gaps at the edges of the range are free or busy.

**Comment by Dunmail** [comment]
Couple of implementation points:

Is the search for: a) slots that start within the range OR b) slots that both start **and** end within the range? 

_i.e._

`slots where slot.start > $args.start and slot.start < $args.end`

OR

`slots where slot.start > $args.start and slot.end < $args.end`

Under the first option, slots at the end of the range will be shown anyway.

Some systems don't store slot end times, rather they store slot start time and slot duration. In these cases, slot end time is a derived value and therefore likely to make the implementation more complex and less efficient. 

Notwithstanding this, including slots at the start of the range is also likely to require 2 searches rather than 1, which will be more complex and less efficient:

```
slots where slot.start > $args.start and slot.start < $args.end
U
slots where slot.start < $args.start and slot.end > $args.start
```
Whilst it's a fair point that it may be useful to see the slot at the lower boundary, is it sufficiently useful to warrant the additional complexity that may be added?

As an I aside, I don't see how it can be used to render a free-busy view as the spec requires that only free slots are returned.

**Comment by jackiebarnes** [comment]
Agree that free slots which span either start or end boundary should be provided

**Comment by Dunmail** [comment]
@jackiebarnes : Even if it makes implementation more complex?

**Comment by briandiggle** [comment]
Scribbled this quick picture to illustrate the question:

![image](https://user-images.githubusercontent.com/7500963/30587780-4d0b3132-9d2c-11e7-996f-ec50a05089b6.png)

The question is what to do with the two free slots marked `?` - should they be included in results?

I imagine a consumer building a view of available bookings. The consumer would expect to present a view in the UI from $args.start to $args.end.

If these two slots marked `?` were included, then a nice UI would need to present the slot start time. There would be added complexity in the consumer to adjust the "UI time window"  to present these slots properly.

Therefore my vote is to exclude any free slots from results which do not fall fully into the time period specified by the client. Whatever we go with , I do think there should be some guidance in the specification so that consumers know what to expect.

**Comment by briandiggle** [comment]
Decision to go with just including the "ticks" in the above picture to favour client simplification- though there are arguments either way. Main thing is just to provide clarity on behaviour for clients.
