### ISSUE TITLE
Register a patient - constrained fhir resources

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#177]
The constrained resource for registering a temporary patient is heavily constrained, 

https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.RegisterPatientResponse/gpconnect-register-patient-1.html

This seems like we are restricting the possible information we can make available to the provider system possibly reducing the use cases that the information can be used for.

Should we allow the consumer to sends additional fields in the patient resource, such as contact information and address, then the provider can take the information they want when they save the temporary patient? If not I assume we should return an error when additional fields such as address are included?

**Comment by michaelmeasures** [comment]
@james-answer there is a decision which needs to be made on exactly what fields can be meaningfully assimilated by the receiving system. If we allow other data such as contact information to be sent then the provider systems needs to be able to store this into the patient's record and it does raise questions about the source of truth (as PDS will also have contact details). I would say it's simpler to not insist at this stage on the 'extra' nice to have details persisted unless it impacts a priority business use-case.

**Comment by Dunmail** [comment]
The GP-Connect profiles should not heavily constrain the data that are sent as this limits differentiation between principal systems. The receiving system should be responsible for publishing guidance around which elements are used so that clients can consider the implications within their workflows.

**Comment by briandiggle** [comment]
The [consumer prerequisites](https://nhsconnect.github.io/gpconnect/foundations_use_case_register_a_patient.html#consumer)  state that the consumer MUST have previously performed a PDS trace. The DOB and other demographics will have been verified with PDS, but the constrained profile does not include NHS number (unlike gpconnect-patient-1), and also address information is not allowed. 
What was the original thinking around the "profiling out" of the demographics fields in gpconnect-register-patient-1, and of not including an NHS Number?

**Comment by michaelmeasures** [comment]
@briandiggle the thinking is that as the provider system is expected to perform a PDS trace when registering the temporary patient we only need to supply from the consumer system the minimal amount of data to allow this to happen. Hence, to ensure a single unique match on PDS all you need is NHS Number and DOB, so that is the absolute hard requirement. We are not aiming to support searching PDS by demographics or other details. It is expected that the provider will take any extra demographic details from PDS directly. From what I can see the constrained [gpconnect-register-patient](https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.RegisterPatientResponse/gpconnect-register-patient-1.html) profile _does_ include the ability to provider any business identifier; so NHS number is already supported - but it's just been left unsliced for some reason (we could get this changed by Data Standards to more restrictive as an NHS number will always be required for this operation).

**Comment by michaelmeasures** [comment]
Please see #74 where there is already a ticket around slicing the business identifier to make it clear that NHS number is mandatory.

**Comment by jackiebarnes** [comment]
Including mandatory NHS Number in DMS change 'package'

**Comment by briandiggle** [comment]
Set of additional optional fields which may be of use as part of the temporary patient record to be identified through:
a) Session with @PeteSalisbury to look at the process in PCS systems.
b) Engagement with practices to validy

**Comment by jackiebarnes** [comment]
JB & JC Proposal:  given that CareConnect-GPC-Patient1 now has Register Patient extension, this resource should replace GPConnect-RegisterPatient-1 resource, thereby offering all the fields on the full GPConnect-constrained Patient;  this is simpler for all developers, less work for Data Stds team, easier to maintain etc

**Comment by james-answer** [comment]
The decision has been made to go with the CareConnect-GPC-Patient1 resource for register patient and not restricting what the consumer can send to the provider. Therefore this no longer seems an issue and can be closed.
