### ISSUE TITLE
Clarify the current position on how API Versioning is to be handled.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#187]
Providers and Consumers SHALL utilise versioning constructs with-in the FHIR standard.

Any breaking changes to an existing API SHALL necessitate a new major API Version to be defined (i.e. moving from DSTU2 to STU3 of the FHIR standard). 

Provider systems SHALL handle API Versioning through the assignment of a new Server Base URL.

New Spine InteractionID(s) SHALL be defined and utilised by Consumers to access the new API via the Spine Security Proxy.

Note, API Versioning in the Server Base URL has been selected to uphold the principle that; as all the logical interactions are defined relative to the service root URL this means that if the address of any one FHIR resource on a system is known, then the address of other resources may be determined.

The overarching design principle being that if the Spine Security Proxy was removed from the end-to-end system architecture then no HTTP headers (other than those defined in the base FHIR or HTTP standards) would be required for API operation.

**Comment by briandiggle** [comment]
[SDS integration provider viewpoint](https://nhsconnect.github.io/gpconnect/integration_spine_directory_service.html#provider-system-viewpoint) implies that the major version in the FHIR Base URL is the full FHIR version.

This needs to clarifying to not refer to the full FHIR version. I.e. _any_ breaking change will result in the bumping of the major version number, and that the uplift to a new version of FHIR is just an example of such a breaking change

Also need to uplift the  [Common API Guidance](https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#service-root-url) to bring this out. 

It is also necessary to clarify that the absence of a major version number in a FHIR Base URL indicates v1 rather than the latest major version.

**Comment by briandiggle** [comment]
Decision was made at the NHS Digital FHIR policy working group:

- version FHIR Endpoints using the FHIR version name (DSTU2, STU3, ..) rather than the numeric FHIR version number (1.0.2 etc).
- include a Major version number of the API after the FHIR version name. Major version will be according to semantic versioning 2 to indicate a breaking change
- FHIR version name shall appear before major version.
- Minor or patch versions will be be included in the FHIR Base URL

FHIR Base URL examples:  version 1 of a FHIR API, running DSTU2:
http://myapi.test.nhs.uk/DSTU/1

A new version of this API is release running STU3:
http://myapi.nhs.test.uk/STU3/2

**Comment by james-answer** [comment]
How would this be represented in the SDS?
How would a consumer find the endpoint for DSTU2  if the provider supports multiple versions?

Would it be a common fhir base url stored in the SDS and the consumer would then append the version before attempting to connect to the endpoint to see if the provider supports the version that they use?

**Comment by briandiggle** [comment]
I guess it would depend on whether the new FHIR server is on the same FQDN and hence the same spine endpoint can be used. The MHS record which contains the FHIR base URL can have multiple values.

But the general approach is referred by by Michael above:
"New Spine InteractionID(s) SHALL be defined and utilised by Consumers to access the new API via the Spine Security Proxy."

**Comment by adamjlees** [comment]
The current approach for this is to register another versioned interaction id in the SDS.
So consumers would lookup the URL endpoint for the DSTU2 interaction or the STU3 and so on.

**Comment by briandiggle** [comment]
Now reflected at [https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#fhir-api-versioning](https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#fhir-api-versioning)
