### ISSUE TITLE
Uplift the SSP HTTP Status Codes to include nginx's 599 Network Connection Timeout error code.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#188]
https://httpstatuses.com/599

**Comment by briandiggle** [comment]
This seems to overlap with a 504 (Gateway Timeout) status code. This is already in the spec at (https://nhsconnect.github.io/gpconnect/integration_spine_security_proxy_implementation_guide.html#functional-requirements)

“If a downstream provider system fails to fulfil a request within a configured timeout period then the connection should be closed and a HTTP timeout response SHALL be returned to the consumer system."

Are there any particular scenarios in view where the SSP (as an single entity from the perspective of the consumer) should return a 599 rather than a 504? 

For example, would a 599 error code denote a timeout from an SSP instance itself, and the 504 is reserved for timeouts at provider endpoints?

**Comment by michaelmeasures** [comment]
@briandiggle it's not totally clear which timeout scenarios trigger exactly which code. However, we came across the 599 error code during DEV testing and it does originate from the Python Tornado library which underpins the SSP. In terms of which is more technically correct 504 or 599 they seem to overlap in intent so a client should really handle both to be as robust as possible (as different technology stacks my prefer one or the other).
