### ISSUE TITLE
VRead currently in scope

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#189]
I asked Michael Measures about the If-None-Match header for reads but that lead to a conversation about VRead, if it is in scope or not in scope. We need to make a decision if VRead is in scope or not in scope.

Content of Mine and Michaels e-mail interaction:

**Me:**
I was just writing tests for VRead on organization and looking through the Fhir specificaiton there is the If-None-Match header which allows the provider system to only return the resource if it has been updated. Are we asking the providers to support this? I know we have included the If-Match header for the create and update operations but there is no mention of the If-None-Match for reads.

**Michael:**
We’ve not asked the providers to implement vread at all… just he vanilla read with the ETag header so you can do an update to the latest version.

**Me:**
In the specification, "Fhir In Scope" section:
https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#fhir-in-scope
In the list of interactions VREAD is included, is the spec incorrect then an VRead should be in the out of scope section?

**Michael:**
It was likely put in-scope early on as it wasn’t clear what each provider would do or could do in this area.

However, since then EMIS have categorically said they will only be supporting reading the latest version (so no historical versions). So it’s definitely not in scope for them and therefore can’t be mandatory…. We could consider either moving it out of scope completely or making it a “MAY” interaction. At this stage I think just moving it out of scope would be best to make it 100% clear it’s not implemented.

**Me:**
The other option is to keep it mandatory, if a provider does not support versioning of resources then they will return the resource if the requested version is the current version, which they should easily be able to check, it the version is not equal to the current version they can return an error. This is how the FHIR specificaiton says people should handle the vread if they do not support versioning.

**Comment by Dunmail** [comment]
There is a deep point of principle here:

Is the GPConnect API to provide EITHER a completely consistent API irrespective of provider OR a broadly consistent API across providers?

I would argue that the latter is both more achievable and useful:

1. Feedback from subsidiary suppliers on the IM2 steering group was that consumers were perfectly happy to manage differences between providers. The consumers will be able to manage the differences that are relevant to them; differences that are relevant for medication reconciliation may be irrelevant to an emergency summary medication list. Experience shows that even with a completely consistent API, there will be variability in the data due to clinical system, organisational practice and individual practice.

2. Where there is opportunity for differentiation amongst suppliers, this should be encouraged as it allows innovation and experimentation. The historic approach of providing a heavily constrained lowest common denominator API has stifled adoption and innovation. FHIR provides a mechanism to handle this. Each provider should provide their own Conformance/CapabilityStatement resource that extends the GPConnect resource to list the actual interactions that their implementation supports; consumers can use this information to adapt their API usage to reflect the implemented system.

**Comment by michaelmeasures** [comment]
Hi @Dunmail I don't disagree with your observation and we haven't said that because it's out of scope for GP Connect phase 1 that it can't be delivered by a provider system. In fact from the outset we have said in the common API guidance that "Vendors are free to implement additional FHIR functionality above that mandated under the GP Connect delivery if they so desire. However, the Spine Security Proxy (SSP) will only forward accredited system interactions.". 

We're also being pragmatic during development on where there is a real tangible constraint (i.e. due to system architecture) that we do allow supplier variation. However, in order to get to the point were the suppliers were willing to develop against the specification we had to put a box around the scope of what we expected them to deliver. We also have to be mindful that as NHSD is commissioning and performing technical accreditation on these APIs that a certain level of technical interoperability and clinical safety has to be reached.

Coming from a development background myself I'm also aware that whilst having an open-ended API specification does give a lot of flexibility to API providers it may not be universally welcomed by consumers as it can set unrealistic expectations as to what functionality will be present. So again whilst I'm all for flexibility and not providing a lowest common denominator API specification if none of the GP system vendors have indicated they're going to support an API feature then I think there is an argument that this should be made clear (and nothing is more clear than removing it from the delivery scope of phase 1).

I also fully agree with your point that the Conformance/CapabilityStatement resource can (and should) be being used by consumer applications to tailor/adapt their API usage. However, I think we're on a bit of a journey with this one as a percentage of consumer applications are immature in terms of FHIR API usage and will be happy to integrate by building a payload from a static XML template (for example). I fully expect this to improve over time but in the short term we have to be realistic that consumers are at all levels of FHIR maturity. Maybe this is something we could look at going forward by writing a tutorial on consumer application best practices to help developers get the most out of the provision of the servers $metadata API.

Also, thanks for the feedback and taking the time to comment on GP Connect 😃

**Comment by Dunmail** [comment]
If SSP only forwards accredited interactions then any additional FHIR functionality provided by principals will available through direct agreement with the principal. What is the vendors view on this? I suggest that:

If the principals *want* to offer additional FHIR functionality through direct agreement, then it is probably easier for consumers to use this for all interactions. This establishes a precedent where SSP is bypassed; in this case SSP may prove to be a rather expensive white elephant. 

If the principals *don't want* to bypass SSP then there isn't a mechanism to add additional functionality and we have a lowest common denominator API. The rate of innovation in the market is driven by NHS-Digital's ability to deliver; the health and care system fails to meet the challenges and citizens receive worse care.

There seems to be an historical parallel with ITK document standards. I remember having to work round the system by sending structured data as an embedded attachment in a Non-coded CDA, to overcome the fact that ITK only allowed transmission of coded data for a small number of interactions. I'd rather not have to be so 'creative' in the use of technology when GP Connect is available!

**Comment by michaelmeasures** [comment]
@Dunmail I wish I had a simple answer on this one... Basically, the general ethos is that eventually suppliers will be able to choose between using the SSP or not for APIs they want to expose. The general plan is that as part of the Digital Interop Platform (DIP) the SSP offering will continue to be refined and joined up with other national services as they come online (such as data sharing, record locator, patient opt-out, staff/citizen identify etc.). There should then be enough value-add that choosing to integration with the DIP/SSP will be compelling for both consumers and API providers. My personal view is that the SSP should eventually evolve/be subsumed into a more general API Management Layer capability (but that's still a long way off). Furthermore, I believe it's on the CareConnectAPI roadmap to look at what role (if any) NHS D will be playing in testing/accreditation of APIs beyond the scope of the GP Connect APIs. One things for sure and that's NHS D doesn't want to slow down the rate of innovation and/or become a bottle neck in the delivery of new API capabilities.

**Comment by james-answer** [comment]
As there is currently no use case identified for requiring VRead, so we are moving it out of scope for the first release.
