### ISSUE TITLE
Book an appointment - Handling of ODS Site Codes

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#198]
The following I think would be useful guidance:

Where an appointment is made associated with a logical organisation ID which refers to a Site within the organisation (with an associated ODS Site code), the created appointment should be assigned a logical ID which is unique within the scope of the organisation. I.e. the logical ID must be unique across all ODS Sites associated with the ODS code of the practice. All Slot IDs referenced in the Appointment resource should also be unique within the scope of the organisation.

**Comment by adamjlees** [comment]
Where an appointment is made [...] the created appointment should be assigned a logical ID which is unique within the scope of the organisation.

@briandiggle Isn't this implicit due to the addressing of FHIR endpoint at ODS code level?

**Comment by james-answer** [comment]
I think both Adam and Brian are correct.

For an Organization where there is a single site:

Organization 1 (LogicalId = 1)
- Org Code "Org1"
- One Site "Site1"

Use: There should be no problem as the logical id for the organization will always be unique.


The problem is when the organization has multiple sites and how they represent the structure of their organization within the organization and site model. The structure could be either of the following two:

**Both sites within one organization:**
Organization 2 (LogicalId = 2)
- Org Code "Org2"
- Two Site "Site2 & Site3"
Use: The appointment ID would have to be unique across both sites as the organization logical id for an appointment at either site would be "2".

The other option is each sight being associate with a different organization object:
Organization 2 (LogicalId = 2)
- Org Code "Org2"
- Two Site "**Site2**"

Organization 2 (LogicalId = 3)
- Org Code "Org2"
- Two Site "**Site3**"

Use: in this example the appointments booked for organization2 at "Site2" should have the organization with logical id "2" but appointments booked with organization2 at "Site3" should have the organization logica id "3". In this situation the appointment logical id could be different for each of the sites as the organization is unique for both.

I think it would be helpful to highlight that the providers need to represent their structure correctly within the resources. If the provider represented there sites as two sites within one organization but actually they were treated seperatly then there would be an issue if they did not have unique appointment logical identifiers over the two sites.

**Comment by jonnyry** [comment]
In EMIS an Organisation with multiple branch sites is represented as follows:

Organisation [GP Surgery]
  Location [Main site]
  Location [Branch site one]
  Location [Branch site two]

The booking of the appointment is done against the Organisation and so appointment logical IDs are unique across the organisation.

**Comment by jonnyry** [comment]
Agreed that Organisation should represent the GP practice as a legal organisation, whereas a Location should represent the physical locations of a GP practice including branch surgeries, and potentially any other customer defined location hierarchy.

Therefore appointment identifiers will not clash between branch sites since these are represented by Location rather than Organisation.

Action - remove ODS Site Code from Organisation.  (This is a Location concept.)

Added to decision log - item number 191 - for wider agreement.
