### ISSUE TITLE
Clarify that a provide system SHOULD return a 501 Not Implemented HTTP Status code if a server interaction hasn't been implemented.

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#208]
We should add the requirement that provider systems SHOULD return a 501 Not Implemented HTTP Status code when access to a given FHIR resource isn't available as it's not (yet) been implemented. This could be added to the [Spine Security Proxy Implementation Guide - Provider Section](https://nhsconnect.github.io/gpconnect/integration_spine_security_proxy_implementation_guide.html#provider). See [HAPI FHIR Exceptions](http://hapifhir.io/apidocs/ca/uhn/fhir/rest/server/exceptions/package-summary.html) for how the HAPI FHIR server utilities a 501 (a server side error) distinct from any 4xx (client side errors).

**Comment by briandiggle** [comment]
@james-answer Do we need changes to the demonstrator provider implementation? Also, do we have any test cases to cover this in the provider test suite?

**Comment by james-answer** [comment]
@briandiggle We would need to change the demonstrator to react like this to requests, I think we care currently returning a 404 as the requested resource is not found.

We have test cases but we will need to change the expected outcome to meet this requirement.

**Comment by james-answer** [comment]
@briandiggle @adamjlees Hi Brian and Adam

I had a question from emis about an error code to go with a 501 if the endpoint is not supported. Do we have an error code to put in the OperationOutcome with a 501 or are we saying a 501 is enough data and we do not need to send back an OperationOutcome if this error occurs?

**Comment by briandiggle** [comment]
Doesn't look like there are any error codes for this scenario. Thinking about adding the following at [Error Handling Guidance](https://nhsconnect.github.io/gpconnect/development_fhir_error_handling_guidance.html)

Other server errors

| HTTP Code | Error Code | Description |
| --------- |------------|-------------|
| 501 | SERVER_NOT_IMPLEMENTED |The requested FHIR resource or FHIR operation has not been implemented by the FHIR server |

**Comment by james-answer** [comment]
@briandiggle - Michael Measures did suggest that me might want to relax the requirement for inclusion of an OperationOutcome in a situation where the HTTP Code is enough to describe the error. For example this where 501 indicates that the requested endpoint has not been implemented. Another example would be read patient for a patient which does not exist, where 404 would indicate that the patient could not be found without really needing an OperationOutcome to supply the same information.

At the start of the project the intention was to only require an OperationOutcome when some additional information would be useful to the consumer but, during the development of access record, for some reason it ended up being that all errors should return an OperationOutcome, probably because for access record there was always more information available which would be useful for error handling.

What would be you opinion on relaxing the requirements and not mandating that all errors have to have an OperationOutcome, only the ones where it adds value to the error response?

**Comment by briandiggle** [comment]
For client development it would seem to be good to stick to a uniform approach that an operationoutcome resource will be present in each case so that a client is more likely to gracefully handle errors.
