### ISSUE TITLE
Extend the JWT "reason_for_request" allowable values to allow other reasons than directcare to be supported in future phases

### ISSUE THREAD

**Issue by michaelmeasures** [nhsconnect/gpconnect#209]
For example we could allow four discrete reasons for request:

- directcare
- secondaryuses
- patientfacing
- urgentcare

GP Connect as it stands remains for 'directcare' only, but the other claims are then available if/when future phases are scoped/planned/implemented or other FHIR API services are implemented that re-use the same JWT format (i.e. the Digital Interop Platform work which is on-going in Domain D).

**Comment by briandiggle** [comment]
As discussed, some clarity is required on the differentiation between directcare and urgentcare

**Comment by devmikey** [comment]
This was suggested as a work around. Decision can't be taken at this time

**Comment by briandiggle** [comment]
Linked to HDL-183.

Since urgent care is essentially a subset of direct care, differentiating between the two values is invalid. Putting it into the value set at this stage may mean having to back it out later.

Decision is to add **patientfacing** only at this time as an additional acceptable value to enable Patient Facing Services use case in future phase of GPConnect

Update https://nhsconnect.github.io/gpconnect/integration_cross_organisation_audit_and_provenance.html#json-web-tokens-jwt

**Comment by james-answer** [comment]
Addition of the "patientfacing" value as an option to "reason_for_request" is covered by issue #299 for uplifting the JWT to support PFS. I am therefore closing this issue as we are not going to add any other options at the current time for the "reason_for_request".
