### ISSUE TITLE
Book Appointment - Cancellation Reason

### ISSUE THREAD

**Issue by wilkinsm** [nhsconnect/gpconnect#224]
We have a requirement to test for the Cancellation Reason on Appointment Book (Requirement BAA-31).

The Cancellation Reason on the Appointment model has a cardinality of 0..1 so it's technically valid for it to exist. (https://data.developer.nhs.uk/fhir/candidaterelease-250816-appts/Profile.GetScheduleQueryResponse/gpconnect-appointment-1.html)

The question has been raised as to whether it should be allowed on Appointment Book?

**Comment by james-answer** [comment]
I cannot think of a use case where you would include a cancellation reason when booking an appointment, especially since we are mandating that the status has to be "booked". If someone wanted to send a cancelled appointment to have a record of an appointment which was cancelled but which was not sent to the provider they could perform a book and then imidiatly a cancel.

**Comment by james-answer** [comment]
In the TA discussion it was decided that the consumer should not pass in the cancellation reason with "Book an appointment". The decision was to not add additional information around what elmeents should not be populated, we should only specify what we want to be populated, therefore there are no specification changes required.
