### ISSUE TITLE
Structure definition Extension-CareConnect-GPC-RegistrationDetails-1 Contains invalid URL values for Child Extensions

### ISSUE THREAD

**Issue by wilkinsm** [nhsconnect/gpconnect#242]
The Structure definition [Extension-CareConnect-GPC-RegistrationDetails-1](https://fhir.nhs.uk/StructureDefinition/Extension-CareConnect-GPC-RegistrationDetails-1) contains incorrect values for it's child extensions as detailed below:

Extension (**registrationPeriod**) url element is marked with a Fixed Value of registrationPeriod.
Assuming this should be "URL: https://fhir.nhs.uk/StructureDefinition/extension-registration-period-1"

Extension (**registrationType**) url element is marked with a Fixed Value of registrationType.
Assuming this should be "URL: https://fhir.nhs.uk/StructureDefinition/extension-registration-type-1"

Extension (**registrationStatus**) url element is marked with a Fixed Value of registrationStatus.
Assuming this should be "URL: https://fhir.nhs.uk/StructureDefinition/extension-registration-status-1"

**Comment by jonnyry** [comment]
Appreciate this looks like a strange extension identifier, but because they are sub elements in a complex extension, they don't need to be URIs.  It's because a complex extension is built using slices on the extension element, and a slice only needs a slice disambiguator - which can be any string.

https://www.hl7.org/fhir/extensibility-examples.html#complex

**Comment by james-answer** [comment]
Closing
