### ISSUE TITLE
[From openhealthhub.org]  Patient identifier system is inconsistent between the resource & API

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#247]
See https://www.openhealthhub.org/t/gp-connect-appointments-patient/381

"Patient.identifier(NHSNumber).system is http://fhir.nhs.net/Id/nhs-number1 but API implementation documentation uses urn:fhir.nhs.uk:id/NHSNumber. I assume urls supersede urns?

Patient.identifier (OtherPatientIdentifier) binding implies use in Scotland (e.g. CHI), but Patient.identifier (NhsNumber) is mandatory. Is there an ambition for the profiles to be used in outside England?"

**Comment by james-answer** [comment]
The patient identifier system is now consistent between the FHIR Resource Profiles and the API specification with the value "https://fhir.nhs.uk/Id/nhs-number".

The current GP Connect profiles contain a slice for the NHS number but the NHS Number business identifier is optional within the profile so other business identifiers could be used instead of the NHS Number if the NHS Number is not available.

The specification has also been changed since the origional issue was raised, the specification now uses the NHS number as an example for all interactions centred around the patient but wording has been updated to make clear that the NHS Number SHALL be supported but providers may support additional business identifiers.

This is therefore no longer an issue as the API and resources can be used outside of England if desired in the future, it is currently out of scope though.

No specification or profiles changes are required so closing the git hub issue.

**Comment by james-answer** [comment]
Added a comment on the origional open health hub issue.
