### ISSUE TITLE
[From openhealthhub.org] Schedule.actor is described as reference(Location|Practitioner) but typed as gpconnect-location-1-0

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect#248]
See first issue on:  https://www.openhealthhub.org/t/gp-connect-appointments-schedule/385

"Schedule.actor is described as reference(Location|Practitioner) but typed as gpconnect-location-1-0

If the Schedule has actor(practitioner) and therefore no actor(location), how will the patient know where to attend?"

**Comment by briandiggle** [comment]
Since this question was posted, the schedule profile https://fhir-test.nhs.uk/StructureDefinition/gpconnect-schedule-1 has been amended, and now contains an optional practitioner extension in addition to the actor which must be a Location reference. 

Whether directly or otherwise, this comment has been addressed!
