### ISSUE TITLE
Search for free slots - implement as REST 

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#266]
Discussions about the rationale behind the use of operations in general RESTful APIs, in this particular example have questioned why this interaction now needs to be implemented as an operation.

The consensus was that interactions should be implemented as operations where there is an overriding reason to divert from the RESTful model, and this clear reason to diverge was not present in this instance.

The following model was agreed:

GET /Schedule?date=01-01-2017
 &date=14-01-2017
 &include=Schedule:actor:Practitioner
 &include=Schedule:actor:Location
 &revinclude=Slot:schedule
&Slot.freeBusyType=free

**Comment by james-answer** [comment]
The example should include the appropriate "eq", "gt", "lt", "ge", "le" search prefixs before each of the date parameters to make them boundaries for the date range.

**Comment by james-answer** [comment]
I was just thinking about this and what we want returning, we want schedule, practitioner, location and slots but only when there is a slot within the requested time period, so if there is no slots in the schedule for the time period we do not want the schedule to be returned, this seems a bit wrong when we are doing a search on the Schedule endpoint and reverse including the slots.

Should we not be doing a search on the Slot endpoint and including schedule then doing a recursive include for the practitioner and location for the included schedules?

GET /Slot?date=ge01-01-2017
&date=le14-01-2017
&Slot.freeBusyType=free
&_include=Slot:schedule
&_include:recurse=Schedule:actor:Practitioner
&_include:recurse=Schedule:actor:Location

**Comment by Dunmail** [comment]
That's reasonable - i.e. the consumer is asking 'what slots are available?'

One thought - would this create a UX problem where there are existing agreements to offer slots? For example, if OOH want to book to a GP practice, how do they differentiate between the cases:
a. where the practice has offered slots but all are taken
b. where the practice isn't offering any slots

**Comment by james-answer** [comment]
For Gp Connect we are treating the two scenarios as the same, because we are only interested in the free slots for the purpose of booking an appointment.

i.e. if there is no slots because they are all busy or if non have been made available it does not make any difference when all you want is a free slot to book an appointment against).

If this is a use case came into scope for GP Connect it would simply be a case of the consumer removing the "Slot.freeBusyType=free" parameter and the provider system should return all the slots free and busy so then the consumer could identify if no slots had been made available or if all the slots were just busy. As the specification stands the response a provider might have to this could vary as all we are going to as them to do is support the free slots so they might return all slots or they might return an error as they are expecting the freeBusy parameter.

**Comment by Dunmail** [comment]
Just reflecting on experience where consumers report a faults on the appointment system because there are no slots available to book when in fact others have already taken them!

**Comment by james-answer** [comment]
Spec updated with final solution so closing issue.
