### ISSUE TITLE
Sending Organization Type & Search Free Slot Filters - Arising from UC Use Case

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#279]
Needed for RESTful Search for Free Slots to support UrgentCare as an organization

**Comment by jackiebarnes** [comment]
This is part of the change originally discussed to support the agreed item in Andrew Michaelson's IUC Appointment Booking v1.3 Recommendations, ie being able to search by Disposition Code and Service Id which was passed to Data Stds for a change to the search filters on the GPConnect-Schedule-Appointment operation, which has now been superseded by the Restful Search.

In addition to the content in his document the following comments reflect previous discussions around this requirement:

20/9/17:  Agreed with D Stds/TAs that we keep the generic SearchFilter which will support Service ID & Disp Code, differentiated by System element, and can be added to with additional search filters in future
19/9/17 James email:  This should be a CodeableConcept value rather than a String value. The system within the CodeableConcept would allow us to identify the specific parameter type.

15/9/17 Jennifer email:  We are not sure that having a generic parameter ‘searchFilter’ is appropriate.  If you reuse this parameter for another purpose the XML would look like this:
• <name value=”searchFilter”/>
• <valueString value=”DX452”/>
• <name value=”searchFilter”/>
• <valueString value=”ABC123”/>
• Therefore you won’t be able to discriminate between the business parameters.  It is better to call the parameter you require something like ‘dispositionCode’ which would reflect the business function

GP Connect will enable IUC Consumers to pass a Disposition code as a filter to search for free slots by adding an optional generic search parameter, ‘searchFilter’ to the gpconnect-schedule-operation-1 profiled OperationDefinition. This will be a CodeableConcept type (0..*) that Consumers may use without breaking existing implementations, or precluding other services’ future use cases.

**Comment by jackiebarnes** [comment]
The relevant content from Andrew's document:

JSON Web Token (JWT)
2.1	Recommendation 1: Urgent Care Consumers use the ‘requesting_organization’ claim to notify Providers that a request comes from an Urgent Care Organisation. This will be meaningful to Consumers and Providers only. This will require an extension to the GP Connect API specification (see next paragraph), but will not have any impact upon the function of the SSP. This extension will also need to be added to the documentation.
The value of ‘requesting_organization’ is an HL7 FHIR DSTU2 Organization. The ‘type’ resource is a CodeableConcept “Example”, meaning instances are not expected or even encouraged to draw from a specific value set. NOTE The following is an example only:
“type”: {
	“coding”: [
		{
			“system”: “http://fhir.nhs.net/Organization/ods-organization-type”,
			“code”: “urgentcare”,
			“display”: “Urgent Care Organization”
		}
	]
}
2.2	Recommendation 2: The GP Connect JWT specification has already been changed for Access Record HTML RC6 so that the ‘requesting_practitioner’ claim has been renamed ‘requesting_identity’ and should be set to a HL7 FHIR DSTU2 Practitioner resource for all ‘Direct Care’ Schedule or Booking requests. There is no restriction upon use of this resource for requests initiated by a call centre worker or other unqualified person in a service that is supporting ‘Direct Care’.
3.	Payload 
3.1.	Recommendation 3:  GP Connect “search for free slots” will be changed to enable IUC Consumers to pass a Disposition code and a Directory of Services Service ID as optional search filters. this will be achieved by adding an additional parameter array to the gpconnect-schedule-operation-1 profiled OperationDefinition and defining two parameters; “searchFilter”, which will be a CodeableConcept type, and “serviceID”, which will be a string to contain a identifier understood by the Consumer and Provider. 
Since these parameters will be optional (0..*), Consumers may use them without breaking existing implementations, or precluding other services’ future use cases. This change will require a Disposition code value set as an extension to the GP Connect FHIR API specification, but will not have any impact upon the function of the SSP. Documentation will need to be updated.
 
NOTE The following is an example only. This depicts how an IUC Consumer might request free slots for a specified Service ID and Disposition code:
"parameter": [
	{
	"name": "searchFilter",
	"coding": [
	{
	"system": "http://fhir.nhs.net/ValueSet/iuc-disposition-1",
	"code": "Dx08",
	"display": "Contact a Primary Care Service within 24 Hours"
	}
	]
	},
	{
	"name": "serviceID",
	"valueString": "0123456789"
	}
]

**Comment by james-answer** [comment]
This issue seems a bit confused and seems to relate to the following three requirements:

1. Adding a new 'type' element coding to the Organization Resource within the JWT to indicate request is from an Urgent Care consumer.
2. Addition of Service ID to "Search for free slots" interaction.
3. Addition of Disposition Code to "Search for free slots" interaction.

Work required to make these changes:
1. Defining the code system for the 'type' element within the requesting organization resource of the JWT will probably need to be done between data standards and GP Connect but this does not require a change to any of the GP Connect resource profiles so this is not imidiatly required for Appointments RC.2.
2 & 3. We have changed the operation to a restful endpoint so the "gpconnect-schedule-operation-1" profile is no longer needed and can be removed by data standards from the fhir reference server. The two new parameters need to be added to the specificaion within the search for free slots page.

**Comment by ahatherly** [comment]
I'm a bit concerned that the JWT - which is an OpenID Connect Authorisation token, and in future will be granted to a client to authorise access to specific types of resource - is being used for a different purpose here; to convey meaning in the ReST call? This is not the purpose of the Access token, which is there to manage the user/security context in which the ReST call is made. Indeed, when in future these tokens are given out by an OpenID Connect authorisation service (e.g. an Principle system's authorisation server authorising access to that system's resources), it will be outside the client's control what goes in it... so it can't be used to add additional semantic meaning to the individual ReST calls. I may be misunderstanding the requirement though?
I do think there may be legitimate cases where "urgent care" could imply different IG controls or permissions for accessing specific types of resources - but in those cases I'd be tempted to use a different "reason_for_request" (e.g. "urgentcare" rather than "directcare") - a range of organisations might offer urgent care services, so it couldn't purely be determined by the org "type"?

**Comment by james-answer** [comment]
@ahatherly I agree this is a miss use of the JWT, I would prefer a new header rather than using anything within the JWT.

The proposals were based on the idea of enabling the use of the GP Connect API for the purpose of urgent care, while minimising the number of changes required to the specification. There is probably still scope to make changes if we feel there is a real issue with the solution.

**Comment by ahatherly** [comment]
If it is a parameter pertinent to the search/request then it should be part of the request itself rather than a header surely?

**Comment by Dunmail** [comment]
ahatherly: +1

My test would be: can you switch JWT/headers and only need to change middleware, rather than business logic?

**Comment by james-answer** [comment]
I suppose since it is currently only applicable to the "search for free slots" interaction, a search parameter would be fine. I was just thinking if we wanted a to identify a consumer as something like urgent care over a number of api calls it would be easier to have a consistent header they can send all the time rather than defining a search parameter on each interaction we find a use case where the provider needs to identify the type of consumer.

**Comment by Dunmail** [comment]
My thoughts:
1. If a principal (_sensu_ security rather than GPSoC) is authenticated & authorised to perform different actions, then this should be reflected in the authorisation claims. The API trusts the auth/z provider and acts accordingly.
2. If the API can switch behaviour based on context (e.g. requester organisation type) then again, this should be reflected in the authorisation claims (an identity claim). Again, the API trusts the auth/z provider and acts accordingly.
3. If the requester is sending information to refine a search then put this is in the search request. The API permits the requester to conduct any searches permitted by the auth/z provider.

**Comment by james-answer** [comment]
After discussion with the TA's it feels like we are trying to achieve Dunmail's second point:

> the API can switch behaviour based on context (e.g. requester organisation type) then again, this should be reflected in the authorisation claims (an identity claim). Again, the API trusts the auth/z provider and acts accordingly.

The current solution is too specific to the urgent care use case, therefore we are going to look at coming up with a more generic solution which would work for other API's and use cases.

**Comment by jackiebarnes** [comment]
Following further discussion on Search Free Slots filters for UC use case, the current spec has hardcoded the Disposition Code and Service Ids for these;  is it possible for a 'non-hardcoded' solution  to accommodate search filters which may be identified for other future use cases?

**Comment by james-answer** [comment]
I have changed the develop branch with a more generic searchFilter parameter which should now contain the sending system type rather than using the JWT, the parameter will repeat to also send the disposition code and service id. We still need to define the valuesets we want to use for each of the instances of the parameter (currently TBC in the spec).

**Comment by jackiebarnes** [comment]
Should this be described as 'Sending System' rather than some form of Organisation - eg Requesting Organisation, Consuming Organisation - what have we used elsewhere in the spec  - trying to achieve consistency?

**Comment by james-answer** [comment]
The agreement on what filter valuesets and implementation guidance will not be finalised for this release so an additional github issue has been raised to cover the remaining work for the next release (#315).

The spec has currently been updated with some guidance on allowing filtering but the specifics have been left open to allow urgent care requiremnets to be implemented by consumers and providers when required within the current version of the specification. The details of this agreed filtering will be added as part of the next specification update.
