### ISSUE TITLE
Update Swagger API Documentation

### ISSUE THREAD

**Issue by briandiggle** [nhsconnect/gpconnect#283]
The swagger API documentation needs updating to bring it inline with the changes made in recent releases to Foundations and Appointments capability packs.

https://nhsconnect.github.io/gpconnect/system_reference_swagger.html

**Comment by briandiggle** [comment]
I notice that the swagger API definition has been removed by the 64fd369 commit.

A swagger definition of the GPConnect API could be of real use to consumers and providers who are looking use it with OpenAPI tools such as code generation for server or client, or test generation tooling. 

It would be good to get a rationale behind removing this before closing this issue.

**Comment by james-answer** [comment]
There was three main reasons for removing it:

1. In the specification we encourage providers and consumers to use open source FhIR libraries, such as HAPI or the standard .NET library, to reduce development time and improve the maturity of these libraries and the FHIR standard. If this is our preferred stance we should not be encouraging them to create code using the swagger definition which would not use any of these FHIR libraries.

2. The original intention of the swagger definition was to allow someone to see the API in a familiar format and also to allow someone to import the definition into Postman so they could play with the functionality. The intention was not for anyone to use it to generate code from. The swagger definition that is currently on the specification is not complete and it is not fully compliant with swagger so if someone did use it to generate code the results would most likely be patchy and would not have all the mandatory elements such as headers.

3. A swagger definition is supposed to be used as documentation of an api, the spec is the specification so having a swagger definition is a duplication of the specification and increases the number of documents which need maintaining as we uplift the specs. The main issue with generating and maintating a swagger definition is that the design of the demonstrator does not allow the swagger definition to be generated automatically because we are using the HAPI FHIR library which has its own annotations which are not recognized by the swagger component. This means that the swagger definition would have to be manually built or we would have to build a swagger definition generating version of the demonstrator which did not use the HAPI FHIR library, even doing this we would need to modify the swagger definition after it was generated as the headers such as Ssp-InteractionId are not associated with specific endpoints so this information would have to be added to the swagger definition.


Based on the fact that we advise the providers and consumers to use open source libraries, the large amount of additional work needed to create and maintain a valid and useful swagger definition is not a sensible use of the GP Connect programs time. The original intention to give a user the ability to see and interact with the API can be achieved with just a postman collection running against the public facing demonstrator instance.

**Comment by adamjlees** [comment]
> In the specification we encourage providers and consumers to use open source FhIR libraries, such as HAPI or the standard .NET library, to reduce development time and improve the maturity of these libraries and the FHIR standard. If this is our preferred stance we should not be encouraging them to create code using the swagger definition which would not use any of these FHIR libraries.

I agree it is our recommendation to use open source FHIR libraries _where they exist_ but by discouraging use of anything but open source FHIR libraries, we are effectively limiting development technology choices to .Net or Java.  We need to be mindful there are other platforms in wide use, especially in healthcare.  Making it more difficult to use these others to develop GP Connect API consumers is going to harm adoption.

**Comment by james-answer** [comment]
Fhir libraries are available in many more languages than .Net and Java, two others are highlighted in the specification already. We do not want to discourage varied technology use but we do want to discourage duplication of effort by re-doing something which has already been done.

**Comment by briandiggle** [comment]
So we agreed:

-  Swagger has some value for some implementation where there a mature FHIR client library is available - Given the likely week work to refactor the GP Connect demonstrator with annotations to support automatic generation of the swagger JSON defintion, this is not a priority at this time
- that we should strengthen current guidance that FHIR reference libraries should be used, and provide concrete rationale describing benefits (which James has done with the 8956b1f commit).

Suggest we close this one now, and put the swagger refactoring onto the demonstrator backlog.

**Comment by ahatherly** [comment]
On a slight tangent - we have some work kicking off to look at API Management tooling within NHS Digital, which may help us with tooling for producing formal API documentation (swagger style). Most of those kinds of tools don't really support the FHIR way of defining an API as yet, but I'm hoping that will change (and we may even be able to contribute to that). I share the slight nervousness over how a developer might use a Swagger definition to generate code, and the risk of that not completely aligning with the formal FHIR API specification.
If we did want something as a stop-gap, has anyone looked at any of the tools that purport to generate swagger definitions directly from Conformance/CapabilityStatements? At least that might slightly reduce the risk of them not being in sync?

**Comment by briandiggle** [comment]
Don't think we've looked at anything that uses the CapabilityStatement - could you suggest example tooling?

**Comment by james-answer** [comment]
Something like the "fhir-swagger" project (https://github.com/bobby-brennan/fhir-swagger) might be worth a look.

I will raise a github issue for additional work on the demonstrator to allow us to get the swagger definition from it.
