### ISSUE TITLE
Patient Temp Address/Contact Details;  Booking Org retention

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#320]
Where are the following requirements called out in the spec:

 if the Consumer sends a patient's temp contact details etc, then the Provider should store these as part of the appointment, and ensure they're not overwritten by any subsequent PDS trace

the Booking Org details should also be stored as part of the appointment?

**Comment by jackiebarnes** [comment]
#278

**Comment by james-answer** [comment]
* The patient contact details would not be sent with the appointment, they would be included in the register patient. The requiremnets have been specified in the "foundations_use_case_register_a_patient.html#payload-request-body" page for register patient.

* The booking org details is specified in the Book Appointmentt page in the Payload Request Body section "appointments_use_case_book_an_appointment.html#payload-request-body".

These two requirements are both covered in the specification.

**Comment by jackiebarnes** [comment]
What happens in the scenario where the consumer wants to book an appointment at a practice which already has an active patient record but needs to send temporary contact information which is different/additional to what it's received from the Provider?

**Comment by james-answer** [comment]
We agreed that this is not possible with the current api, you would need a patient amend or update.

**Comment by jackiebarnes** [comment]
Could this be met by guidance to state that it could be included in Appt Reason, Description or Comment element?

Think it's a bit of a gap;  the req = patient contact details for the purpose of this Appointment;

**Comment by jackiebarnes** [comment]
Re Booking Org - spec includes the req to send this information, but don't think the spec calls out the requirement here, as also in ticket  #304  for the Provider to 'store' rather than just receiving the info

**Comment by james-answer** [comment]
With regards to sending the patient contact details for the appointment in the comment or description was ruled out as even if we say put them in the comment it does not mean that the user will look at the comment if they want to contact the patient. For example, if a schedule has to be cancelled so the receptionist rings everyone who has an appointment on that schedule they will probably look at the patient profile for patient contact details, they most likely would not even open the appointment, so would not see the comment or description. If people wanted to send different contact details in the comment or details they could but it is most likely that they would not be used if there is patient contact details within the patient record.

I think the reason we did not add wording saying that providers should store the Booking Org is because we can not dictate that they store it. When we added the booking organization we were enabling the consumers to send through the information but at that time we were not taking any level of making providers store stuff apart from the must support elements which we felt were required. I think recently our position has changed and we feel we need to request providers store more information if they are sent it, but is this one of those cases?

**Comment by jackiebarnes** [comment]
Understand the above, but these 'requirements' were discussed and agreed in the Decision Log process,  and hence the Booking Org being requested to be part of the FHIR resource, not just for sending purposes, but so that it could ultimately be used.   Hence my assumption that we had included wording in the spec that they should be stored.

**Comment by jackiebarnes** [comment]
Loose end

**Comment by jackiebarnes** [comment]
Temporary DL forum agreed that the bookingOrg STU3 FHIR element should be changed from optional to Must Support, as well as appropriate sub-elements, as well as the 'Created' elements

Patient Temp Contact details for the purposes of the Appointment should be required in Spec to be written to the Appt Comment element with indication of this added to the mandatory Appt Description element, so that the details are retained against the appointment;

**Comment by james-answer** [comment]
I have added wording to the "booking an appointment" page to say consumers SHALL include any temp contact details in the description element. I have also added additional guidance to highlight the must support requirements on the bookingOrganization element.

This is currently in dev and scheduled for release with the next uplift to the spec.

**Comment by jackiebarnes** [comment]
Add wording to FHIR API Guidance page to the effect that FHIR element 'Must Support' properties SHALL apply to any sub-elements and referenced resources

**Comment by james-answer** [comment]
I have added wording around must support being applied to sub elements of elements marked as must support, it is in dev and ready for release with the next spec.

All the changes made now meet the requirements for:
* guidance on Patient temp address and contact details.
* retention of BookingOrganization details

Therefore I am going to close off this issue now.
