### ISSUE TITLE
Add consumer guidance on always sending an Accept header

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect#325]
We need to add guidance for consumers to indicate that they should always send an Accept header so that the provider knows what they should return the response in. Current guidance to providers when they have asked is to default to JSON.

**Comment by adamjlees** [comment]
Current documentation describes use of Accept header or _format parameter.  

Servers SHALL support the optional _format parameter in order to allow the client to specify the response format by its MIME-type. If both are present, the _format parameter overrides the Accept header value in the request.

> Servers SHALL support the optional _format parameter in order to allow the client to specify the response format by its MIME-type. If both are present, the _format parameter overrides the Accept header value in the request.
> 
> Servers SHALL prefer the encoding specified by the Content-Type header if no explicit Accept header has been provided by a client application. 
> 

https://nhsconnect.github.io/gpconnect/development_general_api_guidance.html#content-types

https://nhsconnect.github.io/gpconnect/development_fhir_api_guidance.html#retrieving-a-patient-resource-by-logical-id

**Comment by james-answer** [comment]
It does not describe what should happen on a GET where there is no content-type header and no Accept header or _format parameter is included in the request. We need to add guidance for this scenario for providers to default to json is probably best and guidance to consumers they should always include an Accept header or _format parameter for all requests so that the provider does not ever have to fall back on a default.

**Comment by briandiggle** [comment]
Provider guidance to default to JSON seems sufficient to me, avoiding another consumer requirement.
