### ISSUE TITLE
AM:  Cancellation Reason

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#432]
We are not currently constraining this element to a character limit.  EMIS have reported that their field capacity is 150 chars.  Requesting the information from the other Providers.  We may need to uplift the specification to restrict the number of characters on this element

**Comment by james-answer** [comment]
We should probably just add guidance that providers may truncate the cancellation reason and highlight that different providers have a character limit. There should only be information for administration within this field and its importance is probably reduced due to the fact that the appointment is being cancelled.

**Comment by jackiebarnes** [comment]
Agreed

**Comment by RiChallinor** [comment]
@james-answer to update in 1.2.0
