### ISSUE TITLE
GP Connect API Principles/Design Decisions

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#436]
Need to call out somewhere design/architecture/operating principles eg:

Minimizing complexity for Consumer processing where possible
API's always targeting a single org represented by an ODS code
Each target Org is represented by an individual FHIR Server instance

**Comment by briandiggle** [comment]
We are referring here to a basic principle of API design, which GP connect is following - **that APIs interfaces are designed always with consumers in mind.** The design goal is where possible to present an interface which maximises ease of use for a consumer.

This principle clearly guides the question of where complexity should be found in an API ecosystem. Such an ecosystem sees few "providers" and many "consumers" and therefore it is sensible to place complexity at the provider rather than see a proliferation of complexity in many implementations of the consumer.

Therefore where a design decision is required in which the question of where to place complexity is the key point, the default position is that complexity should be hidden behind the API interface in provider business logic. Complexity should not migrate to the consumer implementation except as an agreed divergence from this principle where there are  demonstrated overriding concerns.

**Comment by jackiebarnes** [comment]
@jonnyry  @briandiggle - Have scanned page and compared to 1.1.1 release content;  can TAs review the substance/wording of what we're trying to get across;  one or two typos;

**Comment by briandiggle** [comment]
@jackiebarnes Content seems good to me
