### ISSUE TITLE
Broken Links to documents 

### ISSUE THREAD

**Issue by MikeStacey** [nhsconnect/gpconnect#471]
The are broken document links on the following pages:

https://nhsconnect.github.io/gpconnect/accessrecord_usecase_3.5.html
https://nhsconnect.github.io/gpconnect/accessrecord_usecase_3.6.html
https://nhsconnect.github.io/gpconnect/accessrecord_usecase_3.22.html

**Comment by tim1ford** [comment]
Fixed in:

https://github.com/nhsconnect/gpconnect/commit/1db1dcef351466265afe0950a330d0fd7d1ec2ee
https://github.com/nhsconnect/gpconnect/commit/f7a16f4c55e07ba49a2e4eef9e78e2ed81fe8cc9
https://github.com/nhsconnect/gpconnect/commit/a1f23e16925b38bf6b972ba7db6aa707b9169433

Updated in develop and master.
