### ISSUE TITLE
Consumer sent temporary contact details for appointment booking

### ISSUE THREAD

**Issue by jackiebarnes** [nhsconnect/gpconnect#592]
Spec meets the requirement for a consumer to be able to send temporary contact details for the purpose of the appointment by indicating that this should be sent in the Appt Description field; 

This reflected the constraints in the spec given that the only opportunity for Consumer to populate the purposed elements for this on the Patient resource was in the Register a Patient API

The Register a Patient API is only used for the scenario where an active Patient record does NOT exist at the target practice therefore not giving 100% opportunity for this info to be sent.    

The original decision was that the Appt Desc should contain an indication of the fact of the temp contact dtls being sent, but that the actual details should be included in the Appt Comment field - see #320;  this was so that at least some indication would be given in the mandatory Desc field, but without potentially exhausting the 100 char constraint, and overloading/constraining the original purpose of this element - to provide a summary of the appt.

#568 reflects consideration of whether to explicitly call out consumer population of this in Register a Patient in the 1.2.2 uplift, which the outcome being no change.

Should we leave the spec for use of Desc only as is, or change to include Comment as above?

**Comment by jackiebarnes** [comment]
Current wording for this is ambiguous:

"If the consumer _**wishes**_ to include patient temporary contact details for the purposes of the appointment they **_SHALL_** include them within the description element of the appointment, so that the details are retained against that specific appointment"

**Comment by jackiebarnes** [comment]
For use case where appt to be booked at a practice which already has an active patient rec (so Register a Patient API and hence patient resource not available) options are:
a) Leave as is -  ie consumer guided that temp contact details shall be added to Appt Desc
b) Provide extension element on Appt resource - impact = FHIR resource amendment;  Book Appt API spec wording; 
 Amend Appt API Spec wording;  Provider handling uplift req'd  for Book, Read/Retrieve, Amend APIs

**Comment by jonnyry** [comment]
As agreed with @jackiebarnes and @MorganB24:

Given the current spec states temporary contact details are placed in an appointment text field (description) and will not be stored properly in the patient demographic record in the provider system, it is less likely they will be seen in the provider system (as this is not normally where a user would go to find contact details), the following has been decided:

- Remove the statements in book and amend appointment around a consumer sending temporary contact details
- Add consumer sending temporary contact details to the Known Issues page:
  - to explain where a consumer is not registering a patient on the provider system, there is a discrepancy that exists because a consumer cannot send temporary contact details
  - that a consumer may send temporary contact details in the description or comment fields, however must be aware that these will not be written to the patient's demographic record in the provider system
- Add a ticket to properly support structured sending of temporary contact details for a future version
