### ISSUE TITLE
•	No general purpose “battery/cluster”

### ISSUE THREAD

**Issue by Fitz1006** [nhsconnect/gpconnect#821]
Emis Web may have non Pathology observations, linked to a header.
The FHIR observation doesn’t seem to allow for the GP2GP battery/cluster approach, so the only option would seem to be to “flatten” the battery/child, ie

                Battery/Investigation : “Some Header”
                                Child observation 1
                                Child observation 2
                                Child observation 3

Would be exported as

                Observation : “Some Header”
                Child observation 1
                Child observation 2
                Child observation 3

**Comment by PeteSalis** [comment]
Spoke to Andy Gaunt at EMIS yesterday afternoon and suggested that any clusters could use the third tier list 'header' to carry the lower level cluster header. 

He seemed happy with the suggestion but to be sure him and Dave Shaw will look at the range of headers that are stored in this way in EMIS and provide a list so that we can check that none will cause us any issues.

**Comment by MikeStacey** [comment]
Added support for uncategorised data in a hierarchy.
